version: '3'
services:
  flask:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: flask
    image: hjavvaji/flask-mongo-python:v1
    restart: unless-stopped
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: mongodbuser
      MONGODB_PASSWORD: mongodbpass
      MONGODB_HOSTNAME: mongodbflask
    ports:
      - "5000:5000"
    volumes:
      - appdata:/var/www
    depends_on:
      - mongodbflask
    networks:
      - frontend
      - backend

  mongodbflask:
    image: mongo:4.0.8
    container_name: mongodbflask
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: mongodbpass
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
