apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodbflask
  namespace: database
spec:
  selector:
    matchLabels:
      app: mongodbflask
  serviceName: mongodb-headless
  template:
    metadata:
      labels:
        app: mongodbflask
    spec:
      serviceAccountName: mongodb
      containers:
      - name: mongodbflask
        image: mongo:4.0.17
        imagePullPolicy: IfNotPresent
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_SERVICE_NAME
          value: "mongodb-headless"
        - name: MONGODB_HOSTNAME
          value: "mongodbflask-0.$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.cluster.local"
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "mongodbuser"
        - name: MONGO_INITDB_DATABASE
          value: "philips"
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-root-password
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongocrud
          mountPath: /data/db
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
  volumeClaimTemplates:
  - metadata:
      name: mongocrud
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
