apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: database
  labels:
    app: mongodbflask
spec:
  clusterIP: None
  selector:
    app: mongodbflask
  ports:
  - port: 27017
    targetPort: 27017
